'''
gptwebapp shows how to create a web app which ask the user for a prompt
and then sends it to openai's GPT API to get a response. You can use this
as your own GPT interface and not have to go through openai's web pages.

We assume that the APIKEY has been put into the shell environment.
Run this server as follows:

On Mac
% pip3 install openai
% pip3 install flask
% export APIKEY="......."  # in bash
% python3 gptwebapp.py

On Windows:
% pip install openai
% pip install flask
% $env:APIKEY="....." # in powershell
% python gptwebapp.py
'''
from flask import request,redirect,url_for,Flask
from gpt import GPT
import os

app = Flask(__name__)
gptAPI = GPT(os.environ.get('APIKEY'))

# Set the secret key to some random bytes. Keep this really secret!
app.secret_key = b'_5#y2L"F4Q789789uioujkkljkl...8z\n\xec]/'

@app.route('/')
def index():
    ''' display a link to the general query page '''
    print('processing / route')
    return f'''
        <h1>GPT Demo</h1>
        <li><a href="{url_for('gptdemo')}">Ask questions to GPT</a></li>
        <li><a href="{url_for('about')}">About</a></li>
        <li><a href="{url_for('team')}">Team</a></li>
        <li><a href="{url_for('gptAngela')}">Angela</a></li>
        <li><a href="{url_for('gptDexin')}">Dexin</a></li>
    '''


@app.route('/gptdemo', methods=['GET', 'POST'])
def gptdemo():
    ''' handle a get request by sending a form
        and a post request by returning the GPT response
    '''
    if request.method == 'POST':
        prompt = request.form['prompt']
        answer = gptAPI.getResponse(prompt)
        return f'''
        <h1>GPT Demo</h1>
        <pre style="bgcolor:yellow">{prompt}</pre>
        <hr>
        Here is the answer in text mode:
        <div style="border:thin solid black">{answer}</div>
        Here is the answer in "pre" mode:
        <pre style="border:thin solid black">{answer}</pre>
        <a href={url_for('gptdemo')}> make another query</a>
        '''
    else:
        return '''
        <h1>GPT Demo App</h1>
        Enter your query below
        <form method="post">
            <textarea name="prompt"></textarea>
            <p><input type=submit value="get response">
        </form>
        '''


@app.route('/about')
def about():
    return f'''
        <h1>About Us</h1>
        <p> This is a program that accepts promt keywords to return the answer generated by gpt! </p>
        '''

@app.route('/team')
def team():
    return f'''
        <h1>Team Members</h1>
        <p> Angela Lam: Senior majoring in Computer Science and Economics </p><br>
        <p> Dexin Huang: Senior majoring in Business </p><br>
        '''

@app.route('/gptAngela', methods=['GET', 'POST'])
def gptAngela():
    ''' handle a get request by sending a form
        and a post request by returning the GPT response
    '''
    if request.method == 'POST':
        prompt = request.form['prompt']
        answer = gptAPI.angela(prompt)
        return f'''
        <h1>Angela's prompt</h1>
        <pre style="bgcolor:yellow">{prompt}</pre>
        <hr>
        Here is the answer in text mode:
        <div style="border:thin solid black">{answer}</div>

        <li><a href={url_for('gptAngela')}> make another query</a></li>
        <li><a href={url_for('gptDexin')}> GPTDexin</a></li>
        <li><a href="{url_for('gptdemo')}">GPT Demo</a></li>
        <li><a href="{url_for('about')}">About</a></li>
        <li><a href="{url_for('team')}">Team</a></li>
        '''
    else:
        return '''
        <h1>Angela's prompt</h1>
        What is the most popular activity in ...
        <form method="post">
            <textarea name="prompt"></textarea>
            <p><input type=submit value="get response">
        </form>
        '''

@app.route('/gptDexin', methods=['GET', 'POST'])
def gptDexin():
    ''' handle a get request by sending a form
        and a post request by returning the GPT response
    '''
    if request.method == 'POST':
        prompt = request.form['prompt']
        answer = gptAPI.dexin(prompt)
        return f'''
        <h1>Dexin's prompt</h1>
        <pre style="bgcolor:yellow">{prompt}</pre>
        <hr>
        Here is the answer in text mode:
        <div style="border:thin solid black">{answer}</div>

        <li><a href={url_for('gptDexin')}> make another query</a></li>
        <li><a href={url_for('gptAngela')}> GPTAngela</a></li>
        <li><a href="{url_for('gptdemo')}">GPT Demo</a></li>
        <li><a href="{url_for('about')}">About</a></li>
        <li><a href="{url_for('team')}">Team</a></li>
        '''
    else:
        return '''
        <h1>Dexin's prompt</h1>
        Respond to the following input in the style of Shakespeare...
        <form method="post">
            <textarea name="prompt"></textarea>
            <p><input type=submit value="get response">
        </form>
        '''

if __name__=='__main__':
    # run the code on port 5001, MacOS uses port 5000 for its own service :(
    app.run(debug=True,port=5001)
